### ISSUE TITLE
Thermostat-EEM ToDo

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-eem#1]
- [x] Hello world
- [x] setup RTIC
- [x] implement hardware/setup structure 
- [x] address LEDs
- [x] configure system timer
- [x] setup networking
     - [x] telemetry
     - [x] settings
- [x] figure out defmt logging
- [x] implement ADCs
- [x] implement TEC drivers
- [x] IIR and input weights/mux
- [ ] Fan PWM and Tacho
- [ ] EEPROM for MAC
- [ ] docstrings for hardware
- [ ] min/max/average per telemetry period
- [ ] ADC debug routine

## Future ToDo in order of importance
- [x] PoE AT mode monitoring (AT_EVENT, POE_PWR_SRC)
- [ ] I2C temperature sensor LM75 setting limits and readout
- [ ] overall current (12V, depending on AT and/or POE or setting) limiting and fan speed setting to manage max current consumption and max board temperature
- [ ] Additional ADC7172 configurations/channels for monitoring/telemetry/characterization: temperature sensor, AIN0123,REF+- single ended in relation to internal reference. https://github.com/quartiq/thermostat-eem/issues/25
- [ ] frontend EEPROM (at least for EUI48)
- [ ] Force EEM SOURCE
- [ ] USB detect
- [ ] USB console
- [ ] Timing analysis
- [ ] More flexible ADC setups (mix of single-ended and differential ratiometric control, sequencing of those flexible setups)
- [ ] Software support for the unipolar output driver variant (unclear if anything is actually needed here).

**Comment by nkrackow** [comment]
I've broken out the missing points into separate issues.
