### ISSUE TITLE
ADC ToDo and sampling/synchronization architecture

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-eem#8]
- [x] check ADC reset does its thing
- [x] impl all chips
- [x] device synchronization between chips
- [x] verifiy all inputs from headboard
- [x] interrupt
- [x] external clock from MCU
